import {
  ToCoreFromWebviewProtocol,
  ToWebviewFromCoreProtocol,
} from "./coreWebview.js";

// Message types to pass through from webview to core
// Note: If updating these values, make a corresponding update in
// extensions/intellij/src/main/kotlin/com/github/qivryn/qivrynintellijextension/toolWindow/QivrynBrowser.kt
export const WEBVIEW_TO_CORE_PASS_THROUGH: (keyof ToCoreFromWebviewProtocol)[] =
  [
    "ping",
    "abort",
    "history/list",
    "history/delete",
    "history/load",
    "history/save",
    "history/clear",
    "agents/list",
    "agents/events",
    "agents/stream",
    "agents/status",
    "agents/control",
    "agents/queue",
    "agents/checkpoints",
    "agents/plans",
    "agents/export",
    "agents/import",
    "agents/automations",
    "agents/automationControl",
    "terminal/jobs",
    "terminal/jobStart",
    "terminal/jobOutput",
    "terminal/jobStop",
    "extensions/skills",
    "extensions/skillSave",
    "extensions/plugins",
    "extensions/pluginInstall",
    "extensions/pluginSetEnabled",
    "extensions/pluginUninstall",
    "browser/grants",
    "browser/grant",
    "browser/revokeGrant",
    "reviews/list",
    "reviews/get",
    "reviews/run",
    "reviews/cancel",
    "reviews/action",
    "reviews/comments",
    "terminal/classify",
    "browser/list",
    "browser/create",
    "browser/action",
    "browser/events",
    "slack/status",
    "slack/authorize",
    "slack/revoke",
    "slack/channels",
    "slack/messages",
    "slack/post",
    "devdata/log",
    "config/addModel",
    "config/newPromptFile",
    "config/newAssistantFile",
    "config/ideSettingsUpdate",
    "config/addLocalWorkspaceBlock",
    "config/addGlobalRule",
    "config/deleteRule",
    "config/getSerializedProfileInfo",
    "config/deleteModel",
    "config/refreshProfiles",
    "config/openProfile",
    "config/updateSharedConfig",
    "config/updateSelectedModel",
    "mcp/reloadServer",
    "mcp/getPrompt",
    "mcp/startAuthentication",
    "mcp/removeAuthentication",
    "mcp/setServerEnabled",
    "context/getContextItems",
    "context/getSymbolsForFiles",
    "context/loadSubmenuItems",
    "context/addDocs",
    "context/removeDocs",
    "context/indexDocs",
    "autocomplete/complete",
    "autocomplete/cancel",
    "autocomplete/accept",
    "nextEdit/predict",
    "nextEdit/reject",
    "nextEdit/accept",
    "nextEdit/startChain",
    "nextEdit/deleteChain",
    "nextEdit/isChainAlive",
    "nextEdit/queue/getProcessedCount",
    "nextEdit/queue/dequeueProcessed",
    "nextEdit/queue/processOne",
    "nextEdit/queue/clear",
    "nextEdit/queue/abort",
    "tts/kill",
    "llm/complete",
    "llm/streamChat",
    "llm/listModels",
    "llm/compileChat",
    "streamDiffLines",
    "chatDescriber/describe",
    "conversation/compact",
    "voice/transcribe",
    "voice/transcribeCancel",
    "voice/captureStart",
    "voice/captureStop",
    "voice/captureCancel",
    "stats/getTokensPerDay",
    "stats/getTokensPerModel",
    // Codebase
    "index/setPaused",
    "index/forceReIndex",
    "index/indexingProgressBarInitialized",
    // Docs, etc.
    "indexing/reindex",
    "indexing/abort",
    "indexing/setPaused",
    "docs/initStatuses",
    "docs/getDetails",
    "docs/getIndexedPages",
    //
    "onboarding/complete",
    "addAutocompleteModel",
    "didChangeSelectedProfile",
    "tools/call",
    "tools/evaluatePolicy",
    "tools/preprocessArgs",
    "isItemTooBig",
    "process/markAsBackgrounded",
    "process/isBackgrounded",
    "process/killTerminalProcess",
    "models/fetch",
  ];

// Message types to pass through from core to webview
// Note: If updating these values, make a corresponding update in
// extensions/intellij/src/main/kotlin/com/github/qivryn/qivrynintellijextension/constants/MessageTypes.kt
export const CORE_TO_WEBVIEW_PASS_THROUGH: (keyof ToWebviewFromCoreProtocol)[] =
  [
    "configUpdate",
    "indexProgress", // Codebase
    "indexing/statusUpdate", // Docs, etc.
    "addContextItem",
    "refreshSubmenuItems",
    "isQivrynInputFocused",
    "setTTSActive",
    "getWebviewHistoryLength",
    "getCurrentSessionId",
    "sessionUpdate",
    "didCloseFiles",
    "toolCallPartialOutput",
  ];
