import {
  FileAttributionStore,
  type AgentLineAttribution,
} from "@continuedev/agent-runtime";
import { getContinueGlobalPath } from "core/util/paths";
import path from "node:path";
import * as vscode from "vscode";

export class AiAttributionCodeLensProvider implements vscode.CodeLensProvider {
  private readonly store = new FileAttributionStore(
    path.join(getContinueGlobalPath(), "attributions"),
  );

  async provideCodeLenses(
    document: vscode.TextDocument,
  ): Promise<vscode.CodeLens[]> {
    if (
      !vscode.workspace
        .getConfiguration("continue")
        .get<boolean>("enableAiAttribution", true)
    ) {
      return [];
    }
    await this.store.initialize();
    const records = await this.store.listForFile(document.uri.fsPath);
    return records.map((record) => {
      const line = Math.max(
        0,
        Math.min(document.lineCount - 1, record.startLine - 1),
      );
      return new vscode.CodeLens(new vscode.Range(line, 0, line, 0), {
        title: "$(sparkle) Continue agent · Open conversation",
        tooltip: `Generated by agent ${record.runId}${record.eventSequence ? ` at event #${record.eventSequence}` : ""}${record.checkpointId ? ` from checkpoint ${record.checkpointId}` : ""}`,
        command: "continue.openAgentAttribution",
        arguments: [record],
      });
    });
  }
}

export async function openAgentAttribution(
  record?: AgentLineAttribution,
): Promise<void> {
  let attribution = record;
  if (!attribution) {
    const editor = vscode.window.activeTextEditor;
    if (!editor) {
      await vscode.window.showInformationMessage(
        "Open a file to inspect AI attribution.",
      );
      return;
    }
    const store = new FileAttributionStore(
      path.join(getContinueGlobalPath(), "attributions"),
    );
    await store.initialize();
    attribution = await store.resolveLine(
      editor.document.uri.fsPath,
      editor.selection.active.line + 1,
    );
  }
  if (!attribution) {
    await vscode.window.showInformationMessage(
      "No Continue agent attribution is recorded for this line.",
    );
    return;
  }
  await vscode.commands.executeCommand(
    "continue.navigateTo",
    `/agents?runId=${encodeURIComponent(attribution.runId)}${attribution.eventSequence ? `&eventSequence=${attribution.eventSequence}` : ""}${attribution.checkpointId ? `&checkpointId=${encodeURIComponent(attribution.checkpointId)}` : ""}`,
    false,
  );
}
