#!/usr/bin/env bash
# setup-continue-providers.sh
#
# Installs the Continue config and .env into ~/.continue so the Continue
# VS Code extension uses the Copilot proxy and OCA paid models.
#
# Usage:
#   bash ~/Documents/continue/scripts/setup-continue-providers.sh
#
# Options:
#   --dry-run     Print what would be done without writing files
#   --env-only    Regenerate ~/.continue/.env only (re-reads OCA token)
#   --copilot-only  Write only Copilot-related config (skip OCA token check)
#
# What it does:
#   1. Creates ~/.continue if it does not exist
#   2. Copies .continue-config/config.yaml → ~/.continue/config.yaml
#   3. Reads ~/.codex/oca-secrets.json and writes OCA_API_KEY to
#      ~/.continue/.env (private, chmod 600)
#
# Re-run any time the OCA token is refreshed:
#   bash ~/.codex/bin/codex-copilot enable          # refresh Copilot auth
#   bash ~/Documents/codex-oca-tool/codex-oca-temp.sh refresh  # refresh OCA
#   bash ~/Documents/continue/scripts/setup-continue-providers.sh --env-only
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd -P)"
CONFIG_SRC="$REPO_DIR/.continue-config/config.yaml"
CONTINUE_DIR="$HOME/.continue"
CONFIG_DST="$CONTINUE_DIR/config.yaml"
ENV_DST="$CONTINUE_DIR/.env"
OCA_SECRETS_FILE="${OCA_SECRETS_FILE:-$HOME/.codex/oca-secrets.json}"
COPILOT_AUTH_FILE="${COPILOT_AUTH_FILE:-$HOME/.codex/copilot-auth.json}"

DRY_RUN=0
ENV_ONLY=0
COPILOT_ONLY=0
for arg in "$@"; do
  case "$arg" in
    --dry-run)    DRY_RUN=1 ;;
    --env-only)   ENV_ONLY=1 ;;
    --copilot-only) COPILOT_ONLY=1 ;;
  esac
done

# ── helpers ──────────────────────────────────────────────────────────────────
log()  { printf '  %s\n' "$*"; }
info() { printf '\033[1;34m▶  %s\033[0m\n' "$*"; }
ok()   { printf '\033[1;32m✓  %s\033[0m\n' "$*"; }
warn() { printf '\033[1;33m⚠  %s\033[0m\n' "$*" >&2; }
err()  { printf '\033[1;31m✗  %s\033[0m\n' "$*" >&2; }

write_file() {
  local dst="$1" content="$2" mode="${3:-644}"
  if [ "$DRY_RUN" = "1" ]; then
    printf '[dry-run] would write %s\n' "$dst"
    return
  fi
  mkdir -p "$(dirname "$dst")"
  printf '%s' "$content" > "$dst"
  chmod "$mode" "$dst"
}

# ── Step 1: create ~/.continue ──────────────────────────────────────────────
info "Checking ~/.continue directory"
if [ ! -d "$CONTINUE_DIR" ]; then
  if [ "$DRY_RUN" = "1" ]; then
    log "would create $CONTINUE_DIR"
  else
    mkdir -p "$CONTINUE_DIR"
    ok "Created $CONTINUE_DIR"
  fi
else
  ok "Directory exists: $CONTINUE_DIR"
fi

# ── Step 2: install config.yaml ──────────────────────────────────────────────
if [ "$ENV_ONLY" = "0" ]; then
  info "Installing config.yaml"
  if [ ! -f "$CONFIG_SRC" ]; then
    err "Source config not found: $CONFIG_SRC"
    exit 1
  fi
  if [ "$DRY_RUN" = "1" ]; then
    log "would copy $CONFIG_SRC → $CONFIG_DST"
  else
    cp -p "$CONFIG_SRC" "$CONFIG_DST"
    ok "Installed: $CONFIG_DST"
  fi
fi

# ── Step 3: read OCA token and write ~/.continue/.env ───────────────────────
if [ "$COPILOT_ONLY" = "0" ]; then
  info "Reading OCA token"
  OCA_KEY=""
  if [ -f "$OCA_SECRETS_FILE" ] && command -v jq >/dev/null 2>&1; then
    OCA_KEY="$(jq -r '.ocaApiKey // empty' "$OCA_SECRETS_FILE" 2>/dev/null || true)"
  fi

  if [ -z "$OCA_KEY" ]; then
    warn "OCA secrets not found or empty: $OCA_SECRETS_FILE"
    warn "Run: bash ~/Documents/codex-oca-tool/codex-oca-temp.sh login"
    warn "Then rerun this script."
    if [ "$ENV_ONLY" = "1" ]; then
      exit 1
    fi
    # Non-fatal: write an empty placeholder so Continue doesn't crash
    OCA_KEY=""
  else
    ok "OCA token found (length=${#OCA_KEY})"
  fi

  ENV_CONTENT="# Continue provider environment variables
# Generated by scripts/setup-continue-providers.sh — do not commit this file.
# Regenerate with: bash scripts/setup-continue-providers.sh --env-only

OCA_API_KEY=${OCA_KEY}
"
  write_file "$ENV_DST" "$ENV_CONTENT" "600"
  [ "$DRY_RUN" = "0" ] && ok "Wrote $ENV_DST (mode 600)"
fi

# ── Step 4: Copilot proxy status ─────────────────────────────────────────────
info "Checking Copilot auth export"
if [ -f "$COPILOT_AUTH_FILE" ]; then
  ok "Copilot auth export present: $COPILOT_AUTH_FILE"
  # Check if proxy is healthy
  if curl -fsS "http://127.0.0.1:8787/health" >/dev/null 2>&1; then
    ok "Copilot proxy is running at http://127.0.0.1:8787/v1"
  else
    warn "Copilot proxy is NOT running."
    warn "Start it with: bash ~/.codex/bin/codex-copilot enable"
  fi
else
  warn "Copilot auth file not found: $COPILOT_AUTH_FILE"
  warn "Run: bash ~/Documents/codex-oca-tool/install.sh --copilot-setup"
  warn "Then accept the VS Code prompt or run: Codex Copilot: Export Token and Enable"
fi

# ── Summary ──────────────────────────────────────────────────────────────────
printf '\n'
info "Summary"
[ "$DRY_RUN" = "1" ]    && log "(dry-run mode — no files were written)"
[ "$ENV_ONLY" = "0" ]   && [ -f "$CONFIG_DST" ] && log "Config  : $CONFIG_DST"
[ "$COPILOT_ONLY" = "0" ] && [ "$DRY_RUN" = "0" ] && log "Env     : $ENV_DST (chmod 600)"
printf '\n'
printf 'Providers available in Continue:\n'
printf '  copilot-proxy  →  http://127.0.0.1:8787/v1/  (Copilot models)\n'
printf '  oca            →  Oracle Code Assist LiteLLM   (OCA models)\n'
printf '\n'
printf 'Reload the Continue extension in VS Code for changes to take effect:\n'
printf '  Developer: Reload Window  (or restart VS Code)\n'
printf '\n'
