import * as fs from "fs";
import * as os from "os";
import * as path from "path";

import { afterEach, beforeEach, describe, expect, test } from "vitest";

import { installBundledConfig } from "./installBundledConfig";

describe("installBundledConfig", () => {
  let root: string;
  let bundledConfigPath: string;
  let configDirectory: string;

  beforeEach(() => {
    root = fs.mkdtempSync(path.join(os.tmpdir(), "qivryn-config-install-"));
    bundledConfigPath = path.join(root, "bundled.yaml");
    configDirectory = path.join(root, ".qivryn");
    fs.writeFileSync(
      bundledConfigPath,
      'name: Qivryn Defaults\nversion: "1.0.0"\nschema: v1\nmodels:\n  - name: Bundled Model\n',
    );
  });

  afterEach(() => {
    fs.rmSync(root, { recursive: true, force: true });
  });

  test("installs the bundled config on a fresh machine", () => {
    expect(installBundledConfig(bundledConfigPath, configDirectory)).toBe(
      "installed",
    );
    expect(
      fs.readFileSync(path.join(configDirectory, "config.yaml"), "utf8"),
    ).toContain("Bundled Model");
  });

  test("replaces the empty config generated by older extension versions", () => {
    fs.mkdirSync(configDirectory, { recursive: true });
    fs.writeFileSync(
      path.join(configDirectory, "config.yaml"),
      "name: Main Config\nversion: 1.0.0\nschema: v1\nmodels: []\n",
    );

    expect(installBundledConfig(bundledConfigPath, configDirectory)).toBe(
      "replaced-empty-default",
    );
    expect(
      fs.readFileSync(path.join(configDirectory, "config.yaml"), "utf8"),
    ).toContain("Bundled Model");
  });

  test("does not overwrite an existing YAML config", () => {
    fs.mkdirSync(configDirectory, { recursive: true });
    const existing = "name: My Config\nmodels:\n  - name: My Model\n";
    fs.writeFileSync(path.join(configDirectory, "config.yaml"), existing);

    expect(installBundledConfig(bundledConfigPath, configDirectory)).toBe(
      "preserved-existing",
    );
    expect(
      fs.readFileSync(path.join(configDirectory, "config.yaml"), "utf8"),
    ).toBe(existing);
  });

  test("does not shadow an existing legacy JSON config", () => {
    fs.mkdirSync(configDirectory, { recursive: true });
    fs.writeFileSync(path.join(configDirectory, "config.json"), "{}");

    expect(installBundledConfig(bundledConfigPath, configDirectory)).toBe(
      "preserved-existing",
    );
    expect(fs.existsSync(path.join(configDirectory, "config.yaml"))).toBe(
      false,
    );
  });
});
